//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGrades.NewGraderInfoService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.radford.edu/NewGrader", ConfigurationName="NewGraderInfoService.NewGraderInfoServiceSoap")]
    public interface NewGraderInfoServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.radford.edu/NewGrader/logIn", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string logIn(string strUsername, string strPassword, string strRole);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.radford.edu/NewGrader/logIn", ReplyAction="*")]
        System.Threading.Tasks.Task<string> logInAsync(string strUsername, string strPassword, string strRole);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.radford.edu/NewGrader/logOut", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string logOut(string strToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.radford.edu/NewGrader/logOut", ReplyAction="*")]
        System.Threading.Tasks.Task<string> logOutAsync(string strToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.radford.edu/NewGrader/saveStudent", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string saveStudent(string p_savemode, WebGrades.NewGraderInfoService.Student p_student, string p_token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.radford.edu/NewGrader/saveStudent", ReplyAction="*")]
        System.Threading.Tasks.Task<string> saveStudentAsync(string p_savemode, WebGrades.NewGraderInfoService.Student p_student, string p_token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.radford.edu/NewGrader/getCourseOfferingsList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable getCourseOfferingsList(string p_mode, string p_token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.radford.edu/NewGrader/getCourseOfferingsList", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> getCourseOfferingsListAsync(string p_mode, string p_token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.radford.edu/NewGrader/getCourseList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable getCourseList(string p_token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.radford.edu/NewGrader/getCourseList", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> getCourseListAsync(string p_token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.radford.edu/NewGrader/getTermList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable getTermList(string p_token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.radford.edu/NewGrader/getTermList", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> getTermListAsync(string p_token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.radford.edu/NewGrader/getCourseOffering", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebGrades.NewGraderInfoService.CourseOffering getCourseOffering(int p_offeringid, string p_token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.radford.edu/NewGrader/getCourseOffering", ReplyAction="*")]
        System.Threading.Tasks.Task<WebGrades.NewGraderInfoService.CourseOffering> getCourseOfferingAsync(int p_offeringid, string p_token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.radford.edu/NewGrader/findStudent", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable findStudent(string p_searchstring, string p_token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.radford.edu/NewGrader/findStudent", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> findStudentAsync(string p_searchstring, string p_token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.radford.edu/NewGrader/getStudent", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebGrades.NewGraderInfoService.Student getStudent(string p_sid, string p_token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.radford.edu/NewGrader/getStudent", ReplyAction="*")]
        System.Threading.Tasks.Task<WebGrades.NewGraderInfoService.Student> getStudentAsync(string p_sid, string p_token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.radford.edu/NewGrader/getStudentClassPerformance", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebGrades.NewGraderInfoService.StudentClassPerformance getStudentClassPerformance(string p_sid, int p_offeringid, string p_token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.radford.edu/NewGrader/getStudentClassPerformance", ReplyAction="*")]
        System.Threading.Tasks.Task<WebGrades.NewGraderInfoService.StudentClassPerformance> getStudentClassPerformanceAsync(string p_sid, int p_offeringid, string p_token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.radford.edu/NewGrader/getTask", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebGrades.NewGraderInfoService.Task getTask(int p_taskid, string p_token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.radford.edu/NewGrader/getTask", ReplyAction="*")]
        System.Threading.Tasks.Task<WebGrades.NewGraderInfoService.Task> getTaskAsync(int p_taskid, string p_token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.radford.edu/NewGrader/getStudentTaskGrade", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebGrades.NewGraderInfoService.StudentTaskGrade getStudentTaskGrade(string p_sid, int p_taskid, string p_token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.radford.edu/NewGrader/getStudentTaskGrade", ReplyAction="*")]
        System.Threading.Tasks.Task<WebGrades.NewGraderInfoService.StudentTaskGrade> getStudentTaskGradeAsync(string p_sid, int p_taskid, string p_token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.radford.edu/NewGrader/changeInstructorPassword", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string changeInstructorPassword(string oldPassword, string newPassword, string securityToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.radford.edu/NewGrader/changeInstructorPassword", ReplyAction="*")]
        System.Threading.Tasks.Task<string> changeInstructorPasswordAsync(string oldPassword, string newPassword, string securityToken);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.radford.edu/NewGrader")]
    public partial class Student : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sIDField;
        
        private string usernameField;
        
        private string firstnameField;
        
        private string lastnameField;
        
        private string nicknameField;
        
        private string notesField;
        
        private string middleinitialField;
        
        private System.Data.DataTable studentDataField;
        
        private System.Data.DataTable studentEnrollmentsField;
        
        private string dbmessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SID {
            get {
                return this.sIDField;
            }
            set {
                this.sIDField = value;
                this.RaisePropertyChanged("SID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string firstname {
            get {
                return this.firstnameField;
            }
            set {
                this.firstnameField = value;
                this.RaisePropertyChanged("firstname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string lastname {
            get {
                return this.lastnameField;
            }
            set {
                this.lastnameField = value;
                this.RaisePropertyChanged("lastname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string nickname {
            get {
                return this.nicknameField;
            }
            set {
                this.nicknameField = value;
                this.RaisePropertyChanged("nickname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string notes {
            get {
                return this.notesField;
            }
            set {
                this.notesField = value;
                this.RaisePropertyChanged("notes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string middleinitial {
            get {
                return this.middleinitialField;
            }
            set {
                this.middleinitialField = value;
                this.RaisePropertyChanged("middleinitial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public System.Data.DataTable studentData {
            get {
                return this.studentDataField;
            }
            set {
                this.studentDataField = value;
                this.RaisePropertyChanged("studentData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public System.Data.DataTable studentEnrollments {
            get {
                return this.studentEnrollmentsField;
            }
            set {
                this.studentEnrollmentsField = value;
                this.RaisePropertyChanged("studentEnrollments");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string dbmessage {
            get {
                return this.dbmessageField;
            }
            set {
                this.dbmessageField = value;
                this.RaisePropertyChanged("dbmessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.radford.edu/NewGrader")]
    public partial class StudentTaskGrade : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string taskTypeField;
        
        private string descriptionField;
        
        private string droppedField;
        
        private decimal maxPointsField;
        
        private decimal pointsEarnedField;
        
        private decimal curvePointsField;
        
        private decimal pointsAssignedField;
        
        private decimal percentageAssignedField;
        
        private System.Data.DataTable studentGradeDataField;
        
        private System.Data.DataTable studentGradeRubricGradesField;
        
        private string dbmessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string taskType {
            get {
                return this.taskTypeField;
            }
            set {
                this.taskTypeField = value;
                this.RaisePropertyChanged("taskType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string dropped {
            get {
                return this.droppedField;
            }
            set {
                this.droppedField = value;
                this.RaisePropertyChanged("dropped");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public decimal maxPoints {
            get {
                return this.maxPointsField;
            }
            set {
                this.maxPointsField = value;
                this.RaisePropertyChanged("maxPoints");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public decimal pointsEarned {
            get {
                return this.pointsEarnedField;
            }
            set {
                this.pointsEarnedField = value;
                this.RaisePropertyChanged("pointsEarned");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public decimal curvePoints {
            get {
                return this.curvePointsField;
            }
            set {
                this.curvePointsField = value;
                this.RaisePropertyChanged("curvePoints");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public decimal pointsAssigned {
            get {
                return this.pointsAssignedField;
            }
            set {
                this.pointsAssignedField = value;
                this.RaisePropertyChanged("pointsAssigned");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public decimal percentageAssigned {
            get {
                return this.percentageAssignedField;
            }
            set {
                this.percentageAssignedField = value;
                this.RaisePropertyChanged("percentageAssigned");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public System.Data.DataTable studentGradeData {
            get {
                return this.studentGradeDataField;
            }
            set {
                this.studentGradeDataField = value;
                this.RaisePropertyChanged("studentGradeData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public System.Data.DataTable studentGradeRubricGrades {
            get {
                return this.studentGradeRubricGradesField;
            }
            set {
                this.studentGradeRubricGradesField = value;
                this.RaisePropertyChanged("studentGradeRubricGrades");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string dbmessage {
            get {
                return this.dbmessageField;
            }
            set {
                this.dbmessageField = value;
                this.RaisePropertyChanged("dbmessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.radford.edu/NewGrader")]
    public partial class Task : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descriptionField;
        
        private string taskTypeField;
        
        private int offeringIDField;
        
        private int maxPointsField;
        
        private int curvePointsField;
        
        private System.Data.DataTable taskRubricPartsField;
        
        private string dbmessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string taskType {
            get {
                return this.taskTypeField;
            }
            set {
                this.taskTypeField = value;
                this.RaisePropertyChanged("taskType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int offeringID {
            get {
                return this.offeringIDField;
            }
            set {
                this.offeringIDField = value;
                this.RaisePropertyChanged("offeringID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int maxPoints {
            get {
                return this.maxPointsField;
            }
            set {
                this.maxPointsField = value;
                this.RaisePropertyChanged("maxPoints");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int curvePoints {
            get {
                return this.curvePointsField;
            }
            set {
                this.curvePointsField = value;
                this.RaisePropertyChanged("curvePoints");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public System.Data.DataTable TaskRubricParts {
            get {
                return this.taskRubricPartsField;
            }
            set {
                this.taskRubricPartsField = value;
                this.RaisePropertyChanged("TaskRubricParts");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string dbmessage {
            get {
                return this.dbmessageField;
            }
            set {
                this.dbmessageField = value;
                this.RaisePropertyChanged("dbmessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.radford.edu/NewGrader")]
    public partial class StudentClassPerformance : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sIDField;
        
        private string gradeOptionField;
        
        private string gradeField;
        
        private string courseNumField;
        
        private string courseNameField;
        
        private string semesterField;
        
        private string sectionNoField;
        
        private string locationField;
        
        private string enrollmentNotesField;
        
        private string offeringNicknameField;
        
        private int offeringIDField;
        
        private System.Data.DataTable studentEnrollmentDataField;
        
        private System.Data.DataTable studentGradesField;
        
        private System.Data.DataTable studentGradeSummaryField;
        
        private System.Data.DataTable studentAttendanceField;
        
        private System.Data.DataTable stuAttendanceSummaryField;
        
        private string dbmessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SID {
            get {
                return this.sIDField;
            }
            set {
                this.sIDField = value;
                this.RaisePropertyChanged("SID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string gradeOption {
            get {
                return this.gradeOptionField;
            }
            set {
                this.gradeOptionField = value;
                this.RaisePropertyChanged("gradeOption");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string grade {
            get {
                return this.gradeField;
            }
            set {
                this.gradeField = value;
                this.RaisePropertyChanged("grade");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string courseNum {
            get {
                return this.courseNumField;
            }
            set {
                this.courseNumField = value;
                this.RaisePropertyChanged("courseNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string courseName {
            get {
                return this.courseNameField;
            }
            set {
                this.courseNameField = value;
                this.RaisePropertyChanged("courseName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string semester {
            get {
                return this.semesterField;
            }
            set {
                this.semesterField = value;
                this.RaisePropertyChanged("semester");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string sectionNo {
            get {
                return this.sectionNoField;
            }
            set {
                this.sectionNoField = value;
                this.RaisePropertyChanged("sectionNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
                this.RaisePropertyChanged("location");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string enrollmentNotes {
            get {
                return this.enrollmentNotesField;
            }
            set {
                this.enrollmentNotesField = value;
                this.RaisePropertyChanged("enrollmentNotes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string offeringNickname {
            get {
                return this.offeringNicknameField;
            }
            set {
                this.offeringNicknameField = value;
                this.RaisePropertyChanged("offeringNickname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public int offeringID {
            get {
                return this.offeringIDField;
            }
            set {
                this.offeringIDField = value;
                this.RaisePropertyChanged("offeringID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public System.Data.DataTable studentEnrollmentData {
            get {
                return this.studentEnrollmentDataField;
            }
            set {
                this.studentEnrollmentDataField = value;
                this.RaisePropertyChanged("studentEnrollmentData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public System.Data.DataTable studentGrades {
            get {
                return this.studentGradesField;
            }
            set {
                this.studentGradesField = value;
                this.RaisePropertyChanged("studentGrades");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public System.Data.DataTable studentGradeSummary {
            get {
                return this.studentGradeSummaryField;
            }
            set {
                this.studentGradeSummaryField = value;
                this.RaisePropertyChanged("studentGradeSummary");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public System.Data.DataTable studentAttendance {
            get {
                return this.studentAttendanceField;
            }
            set {
                this.studentAttendanceField = value;
                this.RaisePropertyChanged("studentAttendance");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public System.Data.DataTable stuAttendanceSummary {
            get {
                return this.stuAttendanceSummaryField;
            }
            set {
                this.stuAttendanceSummaryField = value;
                this.RaisePropertyChanged("stuAttendanceSummary");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string dbmessage {
            get {
                return this.dbmessageField;
            }
            set {
                this.dbmessageField = value;
                this.RaisePropertyChanged("dbmessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.radford.edu/NewGrader")]
    public partial class CourseOffering : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string courseNumField;
        
        private string courseNameField;
        
        private string semesterField;
        
        private string locationField;
        
        private string notesField;
        
        private System.DateTime startDateField;
        
        private int offeringIDField;
        
        private int sectionNoField;
        
        private System.Data.DataTable courseOfferingDataField;
        
        private System.Data.DataTable courseOfferingStudentsField;
        
        private System.Data.DataTable courseOfferingTasksField;
        
        private string dbmessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string courseNum {
            get {
                return this.courseNumField;
            }
            set {
                this.courseNumField = value;
                this.RaisePropertyChanged("courseNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string courseName {
            get {
                return this.courseNameField;
            }
            set {
                this.courseNameField = value;
                this.RaisePropertyChanged("courseName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string semester {
            get {
                return this.semesterField;
            }
            set {
                this.semesterField = value;
                this.RaisePropertyChanged("semester");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
                this.RaisePropertyChanged("location");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string notes {
            get {
                return this.notesField;
            }
            set {
                this.notesField = value;
                this.RaisePropertyChanged("notes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public System.DateTime startDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
                this.RaisePropertyChanged("startDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int offeringID {
            get {
                return this.offeringIDField;
            }
            set {
                this.offeringIDField = value;
                this.RaisePropertyChanged("offeringID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int sectionNo {
            get {
                return this.sectionNoField;
            }
            set {
                this.sectionNoField = value;
                this.RaisePropertyChanged("sectionNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public System.Data.DataTable courseOfferingData {
            get {
                return this.courseOfferingDataField;
            }
            set {
                this.courseOfferingDataField = value;
                this.RaisePropertyChanged("courseOfferingData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public System.Data.DataTable courseOfferingStudents {
            get {
                return this.courseOfferingStudentsField;
            }
            set {
                this.courseOfferingStudentsField = value;
                this.RaisePropertyChanged("courseOfferingStudents");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public System.Data.DataTable courseOfferingTasks {
            get {
                return this.courseOfferingTasksField;
            }
            set {
                this.courseOfferingTasksField = value;
                this.RaisePropertyChanged("courseOfferingTasks");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string dbmessage {
            get {
                return this.dbmessageField;
            }
            set {
                this.dbmessageField = value;
                this.RaisePropertyChanged("dbmessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NewGraderInfoServiceSoapChannel : WebGrades.NewGraderInfoService.NewGraderInfoServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NewGraderInfoServiceSoapClient : System.ServiceModel.ClientBase<WebGrades.NewGraderInfoService.NewGraderInfoServiceSoap>, WebGrades.NewGraderInfoService.NewGraderInfoServiceSoap {
        
        public NewGraderInfoServiceSoapClient() {
        }
        
        public NewGraderInfoServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NewGraderInfoServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NewGraderInfoServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NewGraderInfoServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string logIn(string strUsername, string strPassword, string strRole) {
            return base.Channel.logIn(strUsername, strPassword, strRole);
        }
        
        public System.Threading.Tasks.Task<string> logInAsync(string strUsername, string strPassword, string strRole) {
            return base.Channel.logInAsync(strUsername, strPassword, strRole);
        }
        
        public string logOut(string strToken) {
            return base.Channel.logOut(strToken);
        }
        
        public System.Threading.Tasks.Task<string> logOutAsync(string strToken) {
            return base.Channel.logOutAsync(strToken);
        }
        
        public string saveStudent(string p_savemode, WebGrades.NewGraderInfoService.Student p_student, string p_token) {
            return base.Channel.saveStudent(p_savemode, p_student, p_token);
        }
        
        public System.Threading.Tasks.Task<string> saveStudentAsync(string p_savemode, WebGrades.NewGraderInfoService.Student p_student, string p_token) {
            return base.Channel.saveStudentAsync(p_savemode, p_student, p_token);
        }
        
        public System.Data.DataTable getCourseOfferingsList(string p_mode, string p_token) {
            return base.Channel.getCourseOfferingsList(p_mode, p_token);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> getCourseOfferingsListAsync(string p_mode, string p_token) {
            return base.Channel.getCourseOfferingsListAsync(p_mode, p_token);
        }
        
        public System.Data.DataTable getCourseList(string p_token) {
            return base.Channel.getCourseList(p_token);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> getCourseListAsync(string p_token) {
            return base.Channel.getCourseListAsync(p_token);
        }
        
        public System.Data.DataTable getTermList(string p_token) {
            return base.Channel.getTermList(p_token);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> getTermListAsync(string p_token) {
            return base.Channel.getTermListAsync(p_token);
        }
        
        public WebGrades.NewGraderInfoService.CourseOffering getCourseOffering(int p_offeringid, string p_token) {
            return base.Channel.getCourseOffering(p_offeringid, p_token);
        }
        
        public System.Threading.Tasks.Task<WebGrades.NewGraderInfoService.CourseOffering> getCourseOfferingAsync(int p_offeringid, string p_token) {
            return base.Channel.getCourseOfferingAsync(p_offeringid, p_token);
        }
        
        public System.Data.DataTable findStudent(string p_searchstring, string p_token) {
            return base.Channel.findStudent(p_searchstring, p_token);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> findStudentAsync(string p_searchstring, string p_token) {
            return base.Channel.findStudentAsync(p_searchstring, p_token);
        }
        
        public WebGrades.NewGraderInfoService.Student getStudent(string p_sid, string p_token) {
            return base.Channel.getStudent(p_sid, p_token);
        }
        
        public System.Threading.Tasks.Task<WebGrades.NewGraderInfoService.Student> getStudentAsync(string p_sid, string p_token) {
            return base.Channel.getStudentAsync(p_sid, p_token);
        }
        
        public WebGrades.NewGraderInfoService.StudentClassPerformance getStudentClassPerformance(string p_sid, int p_offeringid, string p_token) {
            return base.Channel.getStudentClassPerformance(p_sid, p_offeringid, p_token);
        }
        
        public System.Threading.Tasks.Task<WebGrades.NewGraderInfoService.StudentClassPerformance> getStudentClassPerformanceAsync(string p_sid, int p_offeringid, string p_token) {
            return base.Channel.getStudentClassPerformanceAsync(p_sid, p_offeringid, p_token);
        }
        
        public WebGrades.NewGraderInfoService.Task getTask(int p_taskid, string p_token) {
            return base.Channel.getTask(p_taskid, p_token);
        }
        
        public System.Threading.Tasks.Task<WebGrades.NewGraderInfoService.Task> getTaskAsync(int p_taskid, string p_token) {
            return base.Channel.getTaskAsync(p_taskid, p_token);
        }
        
        public WebGrades.NewGraderInfoService.StudentTaskGrade getStudentTaskGrade(string p_sid, int p_taskid, string p_token) {
            return base.Channel.getStudentTaskGrade(p_sid, p_taskid, p_token);
        }
        
        public System.Threading.Tasks.Task<WebGrades.NewGraderInfoService.StudentTaskGrade> getStudentTaskGradeAsync(string p_sid, int p_taskid, string p_token) {
            return base.Channel.getStudentTaskGradeAsync(p_sid, p_taskid, p_token);
        }
        
        public string changeInstructorPassword(string oldPassword, string newPassword, string securityToken) {
            return base.Channel.changeInstructorPassword(oldPassword, newPassword, securityToken);
        }
        
        public System.Threading.Tasks.Task<string> changeInstructorPasswordAsync(string oldPassword, string newPassword, string securityToken) {
            return base.Channel.changeInstructorPasswordAsync(oldPassword, newPassword, securityToken);
        }
    }
}
